name: stock_bar
description: Control de stock y previsión de reposición para el bar.
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0
  intl: ^0.19.0

flutter:
  uses-material-design: true
